Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

if rtconfig.BOARD == 'os0_rcpu':
	src = [
		'main.c',
	]
	CPPPATH = [
		cwd,
	]
elif rtconfig.BOARD == 'os1_rcpu':
	src = [
		'rt-diff-motor-control/control_main.c',
		'rt-diff-motor-control/src/motor_pwm.c',
		'rt-diff-motor-control/src/motor_gpio.c',
		'rt-diff-motor-control/src/encoder.c',
		'rt-diff-motor-control/src/motor_control.c',
		'rt-diff-motor-control/src/led_test.c',
		'rt-diff-motor-control/src/pid.c',
		'rt-diff-motor-control/src/rpmsg_test.c',
		'rt-diff-motor-control/src/rpmsg_motor.c',
	]
	CPPPATH = [
		cwd,
		cwd + '/rt-diff-motor-control/include',
	]
else:
	src = Glob('*.c')
	CPPPATH = [
		cwd,
	]

CCFLAGS = ' -c -ffunction-sections'

group   = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CCFLAGS=CCFLAGS)

Return('group')
